CREATE TABLE IF NOT EXISTS korzinka_db.c_device (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    device_manufacturer VARCHAR(255),
    device_model VARCHAR(255),
    device_type VARCHAR(255),
    _lch TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

--create primary key
DO $$ BEGIN
IF NOT EXISTS (
	SELECT 1
	FROM information_schema.table_constraints
	WHERE table_schema = 'korzinka_db'
	AND table_name = 'c_device'
	AND constraint_type = 'PRIMARY KEY'
	LIMIT 1
)
THEN
	ALTER TABLE IF EXISTS korzinka_db.c_device
		ADD CONSTRAINT pk_c_device_id
		PRIMARY KEY (id);
END IF;
END $$;

COMMENT ON TABLE korzinka_db.c_device IS 'reference table of devices';

COMMENT ON COLUMN korzinka_db.c_device.id IS 'identifier';
COMMENT ON COLUMN korzinka_db.c_device.device_manufacturer IS 'manufacturer';
COMMENT ON COLUMN korzinka_db.c_device.device_model IS 'model';
COMMENT ON COLUMN korzinka_db.c_device.device_type IS 'type';
