CREATE TABLE IF NOT EXISTS korzinka_db.c_location (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    country_iso_code VARCHAR(255),
    city VARCHAR(255),
    _lch TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

--create primary key
DO $$ BEGIN
IF NOT EXISTS (
	SELECT 1
	FROM information_schema.table_constraints
	WHERE table_schema = 'korzinka_db'
	AND table_name = 'c_location'
	AND constraint_type = 'PRIMARY KEY'
	LIMIT 1
)
THEN
	ALTER TABLE IF EXISTS korzinka_db.c_location
		ADD CONSTRAINT pk_c_location_id
		PRIMARY KEY (id);
END IF;
END $$;

COMMENT ON TABLE korzinka_db.c_location IS 'reference table of location';

COMMENT ON COLUMN korzinka_db.c_location.id IS 'identifier';
COMMENT ON COLUMN korzinka_db.c_location.country_iso_code IS 'code';
COMMENT ON COLUMN korzinka_db.c_location.city IS 'city';
