CREATE TABLE IF NOT EXISTS korzinka_db.c_publisher (
    publisher_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    publisher_name VARCHAR(255),
    _lch TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

--create primary key
DO $$ BEGIN
IF NOT EXISTS (
	SELECT 1
	FROM information_schema.table_constraints
	WHERE table_schema = 'korzinka_db'
	AND table_name = 'c_publisher'
	AND constraint_type = 'PRIMARY KEY'
	LIMIT 1
)
THEN
	ALTER TABLE IF EXISTS korzinka_db.c_publisher
		ADD CONSTRAINT pk_c_publisher_id
		PRIMARY KEY (publisher_id);
END IF;
END $$;

COMMENT ON TABLE korzinka_db.c_publisher IS 'reference table of publishers';

COMMENT ON COLUMN korzinka_db.c_publisher.publisher_id IS 'identifier';
COMMENT ON COLUMN korzinka_db.c_publisher.publisher_name IS 'name';
