CREATE TABLE IF NOT EXISTS korzinka_db.c_track (
    tracking_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tracker_name VARCHAR(255),
    _lch TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

--create primary key
DO $$ BEGIN
IF NOT EXISTS (
	SELECT 1
	FROM information_schema.table_constraints
	WHERE table_schema = 'korzinka_db'
	AND table_name = 'c_track'
	AND constraint_type = 'PRIMARY KEY'
	LIMIT 1
)
THEN
	ALTER TABLE IF EXISTS korzinka_db.c_track
		ADD CONSTRAINT pk_c_track_id
		PRIMARY KEY (tracking_id);
END IF;
END $$;

COMMENT ON TABLE korzinka_db.c_track IS 'reference table of track';

COMMENT ON COLUMN korzinka_db.c_track.tracking_id IS 'identifier';
COMMENT ON COLUMN korzinka_db.c_track.tracker_name IS 'name';
