CREATE TABLE IF NOT EXISTS korzinka_db.user_tracking_logs (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    application_id BIGINT,
    publisher_id BIGINT,
    tracking_id BIGINT,
    click_timestamp TIMESTAMP WITHOUT TIME ZONE,
    click_datetime TIMESTAMP WITHOUT TIME ZONE,
    click_ipv6 VARCHAR(255),
    click_url_parameters VARCHAR(255),
    click_id VARCHAR(255),
    click_user_agent TEXT,
    ios_ifa VARCHAR(255),
    ios_ifv VARCHAR(255),
    android_id VARCHAR(255),
    google_aid VARCHAR(255),
    os_id BIGINT,
    device_id BIGINT,
    is_bot BOOLEAN,
    location_id BIGINT,
    _lch TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
);

--create primary key
DO $$ BEGIN
IF NOT EXISTS (
	SELECT 1
	FROM information_schema.table_constraints
	WHERE table_schema = 'korzinka_db'
	AND table_name = 'user_tracking_logs'
	AND constraint_type = 'PRIMARY KEY'
	LIMIT 1
)
THEN
	ALTER TABLE IF EXISTS korzinka_db.user_tracking_logs
		ADD CONSTRAINT pk_user_tracking_logs_id
		PRIMARY KEY (id);
END IF;
END $$;

--create fk publisher_id
ALTER TABLE korzinka_db.user_tracking_logs DROP CONSTRAINT IF EXISTS fk_user_tracking_logs_publisher_id;
ALTER TABLE korzinka_db.user_tracking_logs ADD CONSTRAINT fk_user_tracking_logs_publisher_id FOREIGN KEY(publisher_id) REFERENCES korzinka_db.c_publisher(id);
CREATE INDEX IF NOT EXISTS idx_user_tracking_logs_publisher_id ON korzinka_db.user_tracking_logs USING btree (publisher_id);

--create fk tracking_id
ALTER TABLE korzinka_db.user_tracking_logs DROP CONSTRAINT IF EXISTS fk_user_tracking_logs_tracking_id;
ALTER TABLE korzinka_db.user_tracking_logs ADD CONSTRAINT fk_user_tracking_logs_tracking_id FOREIGN KEY(tracking_id) REFERENCES korzinka_db.c_track(id);
CREATE INDEX IF NOT EXISTS idx_user_tracking_logs_tracking_id ON korzinka_db.user_tracking_logs USING btree (tracking_id);

--create fk os_id
ALTER TABLE korzinka_db.user_tracking_logs DROP CONSTRAINT IF EXISTS fk_user_tracking_logs_os_id;
ALTER TABLE korzinka_db.user_tracking_logs ADD CONSTRAINT fk_user_tracking_logs_os_id FOREIGN KEY(os_id) REFERENCES korzinka_db.c_os(id);
CREATE INDEX IF NOT EXISTS idx_user_tracking_logs_os_id ON korzinka_db.user_tracking_logs USING btree (os_id);

--create fk device_id
ALTER TABLE korzinka_db.user_tracking_logs DROP CONSTRAINT IF EXISTS fk_user_tracking_logs_device_id;
ALTER TABLE korzinka_db.user_tracking_logs ADD CONSTRAINT fk_user_tracking_logs_device_id FOREIGN KEY(device_id) REFERENCES korzinka_db.c_device(id);
CREATE INDEX IF NOT EXISTS idx_user_tracking_logs_device_id ON korzinka_db.user_tracking_logs USING btree (device_id);

--create fk location_id
ALTER TABLE korzinka_db.user_tracking_logs DROP CONSTRAINT IF EXISTS fk_user_tracking_logs_location_id;
ALTER TABLE korzinka_db.user_tracking_logs ADD CONSTRAINT fk_user_tracking_logs_location_id FOREIGN KEY(location_id) REFERENCES korzinka_db.c_location(id);
CREATE INDEX IF NOT EXISTS idx_user_tracking_logs_location_id ON korzinka_db.user_tracking_logs USING btree (location_id);

COMMENT ON TABLE korzinka_db.user_tracking_logs IS 'tracking logs of users';

COMMENT ON COLUMN korzinka_db.user_tracking_logs.id IS 'identifier';
